### ISSUE TITLE
Do JS styling changes in openst-platform of follow the common style guide followed across all openst repos.

### ISSUE THREAD

**Issue by rachinkapoor** [OpenSTFoundation/openst-notification#18]
PROBLEM : Making sure a coding style is properly followed is a big undertaking, it often slips through the cracks leaving the work inconsistent across repos.

SOLUTION
We came across Prettier https://prettier.io/ that automatically style the code. This will help the codebase be uniform and easier to read alongwith saving good amount of our time.

Prettier suppors:

JavaScript, including ES2017
JSX
Flow
TypeScript
CSS, Less, and SCSS
JSON
GraphQL
Markdown, including GFM
YAML
It removes all original styling and ensures the outputted code conforms to a consistent style. (See this post)

**Comment by santhu210** [comment]
Changes to integrate prettier are done and committed. Resolving issue
